---
- name: install docker to CentOS
  ansible.builtin.yum:
    name:
      - epel-release
      - yum-utils
    state: installed
  when: ansible_facts['distribution'] == "CentOS"

- name: config repo
  shell: yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts['distribution'] == "CentOS"

- name: install docker to CentOS
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: installed
  when: ansible_facts['distribution'] == "CentOS"  

- name: apt update
  shell: apt update
  when: ansible_facts['distribution'] == "Ubuntu"

- name: apt-get install
  shell: apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
  when: ansible_facts['distribution'] == "Ubuntu"

- name: mkdir
  shell: mkdir -p /etc/apt/keyrings
  when: ansible_facts['distribution'] == "Ubuntu"

- name: add Dockers official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: ansible_facts['distribution'] == "Ubuntu"

- name: add Dockers official GPG key
  shell: echo \
         '"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'
  when: ansible_facts['distribution'] == "Ubuntu"

- name: apt upgrade
  shell: apt upgrade
  when: ansible_facts['distribution'] == "Ubuntu"

- name: install docker-ce
  shell: apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
  when: ansible_facts['distribution'] == "Ubuntu"  
