---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  
- name: install pg on ubu
  ansible.builtin.apt:
    name:
      - "{{pg_version}}"
      - postgresql-contrib
    state: latest

- name: copy congif pg
  template:
    src: "{{ item.template }}"
    dest: "{{data_directory}}/{{ item.name }}"
    owner: postgres
    group: postgres
    backup: no
  with_items:
    - { name: 'postgresql.conf', template: 'postgresql.conf.j2' }
  notify: Restart postgresql
